spring:
  application:
    name: ${DOMAIN_NAME}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queue:
  name: ResultadoVotacaoQueue

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
security:
  user:
    password: ${eureka.password}

app:
  name: Pauta MS
  api:
    title: Pauta microservice
    version: 1.0.0
    description: Pauta microservice
    base-package: com.assembleia.pautams.controller
    contact-name: Fabio Marsiaj
    contact-email: fabiobackend@gmail.com
    swagger:
      enable: true

---

spring:
  application:
    name: ${DOMAIN_NAME}
  swagger:
    enable: false
  rabbitmq:
    host: shrimp.rmq.cloudamqp.com
    uri: amqps://${RABBIT_USER}:${RABBIT_PASSWORD}@shrimp.rmq.cloudamqp.com/${RABBIT_USER}
    ports:
      - "5672:5672"
      - "15672:15672"
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    queue: SISTEMA_DE_VOTOS_QUEUE
    exchange: SISTEMA_DE_VOTOS_EXCHANGE
    routingKey: SISTEMA_DE_VOTOS_ROUTING_KEY
    ssl:
      enabled: true
  data:
    mongodb:
      uri: ${MONGODB_URI}

associado-ms:
  ribbon:
    listOfServers: associado-ms.herokuapp.com

queue:
  name: ResultadoVotacaoQueue

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}





