spring:
  application:
    name: pauta-ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  name: teste

server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

associado-ms:
  ribbon:
    listOfServers: localhost:8001,localhost:8002
    connectTimeout: 10000
    readTimeout: 20000

