spring:
  application:
    name: associado-ms
  data:
    mongodb:
      uri: mongodb+srv://fabioqmarsiaj:9Q3ZrRPxKo3XJm5a@controledevotosdb.mke9i.mongodb.net/?retryWrites=true&w=majority

server:
  port: 8001
  additionalPorts: 8002

eureka:
  client:
  service-url:
  defaultZone: http://localhost:8761/eureka





