eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
security:
  user:
    password: ${eureka.password}

app:
  name: Associado MS
  api:
    title: Associado microservice
    version: 1.0.0
    description: Associado microservice
    base-package: com.assembleia.associadoms.controller
    contact-name: Fabio Marsiaj
    contact-email: fabiobackend@gmail.com
    swagger:
      enable: true

---

spring:
  application:
    name: ${DOMAIN_NAME}
  data:
    mongodb:
      uri: ${MONGODB_URI}
  swagger:
    enable: false

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}





