eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
security:
  user:
    password: ${eureka.password}

---

spring:
  application:
    name: ${DOMAIN_NAME}
  data:
    mongodb:
      uri: ${MONGODB_URI}

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}





